export enum ModuleEnum {
	DASHBOARD = "DASHBOARD",
	QUESTIONS = "QUESTIONS",
	USER = "USER",
	ROLE = "ROLE",
	AUTH = "AUTH",
	STATUS = "STATUS",
	APP = "APP",
	CONSIGNEE = "CONSIGNEE",
	OTP = "OTP",
}
